# Generated by Django 5.1.7 on 2025-03-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='date_joined',
            new_name='date_created',
        ),
    ]
